name: CI/CD Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches: [$default-branch]
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  github_update:
    name: check if there are any updates
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - name: Check for updates
        run: |
          git fetch --all
          git diff --name-only origin/$default-branch
      